import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import "./globals.css";
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";
import QueryProvider from "@/lib/providers/QueryProvider";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased overflow-x-hidden`}>
        <QueryProvider>
          <div className="flex flex-col mx-auto min-h-screen items-center">
            <Header />
            {children}
            <Footer />
          </div>
        </QueryProvider>
      </body>
    </html>
  );
}